### ISSUE TITLE
S63toS57

### ISSUE THREAD

**Issue by y0913011011** [pavelpasha/s63lib#2]
Can this code convert S63 data to S57? or What is the purpose of this project?

**Comment by pavelpasha** [comment]
Yes. This is the main purpose of this project. S63 cell actually not the different format, it the same format as s57 is, but compressed with .zip and encrypted with a blowfish algorithm. You can read this paper [https://github.com/pavelpasha/s63lib/blob/master/doc/S-63_e1.2.0_EN_Jan2015.pdf]() to get detailed information how the s63 protection scheme works. 
In order to decrypt it back, you need to know two things: a CELLPERMIT and HWID.
Lets assume you have it. There is the s63.h file In this repository, which declares a few usefull functions.
First of all you need to extract a cellkeys from from CELLPERMIT with this function:
`static std::pair<std::string,std::string> extractCellKeysFromCellpermit(const std::string& cellpermit, const std::string& HW_ID, bool& ok);`
You pass to it your CELLPERMIT and HWID and it returns you a pair of cellkeys.
With those cellkeys you can finally decpypt your s63 cell. 
`static S63Error decryptAndUnzipCellByKey(const std::string& in_path, const std::pair<std::string, std::string>& keys, const std::string& out_path);`
First argument - path of your s63 cell; second - cellkeys; third - the path where your s57 cell you want to be saved.

For example:
```
string example_hw_id = "12348";// 3132333438 (HEX)
string example_cellpermit = "NO4D061320000830BEB9BFE3C7C6CE68B16411FD09F96982795C77B204F54D48";
string s63_cell_path = "s63/NO4D06/NO4D06.000"
string output_cell_path = "s57/NO4D06/NO4D06.000"
bool ok;
auto cell_keys = S63::extractCellKeysFromCellpermit(test_cellpermit, test_hw_id, ok);
if(!ok) printf("error\n");
auto error = S63::decryptAndUnzipCellByKey(s63_cell_path, cell_keys, output_cell_path);
```
