### ISSUE TITLE
create a permit.txt

### ISSUE THREAD

**Issue by y0913011011** [pavelpasha/s63lib#3]
Dear sir:
how can i create a permit.txt with this project?

**Comment by pavelpasha** [comment]
A PERMIT.TXT contains a list of cellpermits and some meta information. (You can find more detailed information on page 14 of [this](https://github.com/pavelpasha/s63lib/blob/master/doc/S-63_e1.2.0_EN_Jan2015.pdf) document)
It looks like:
```
:DATE 20080809 11:11
:VERSION 2
:ENC
[List of licenced cell permits for official ENCs]
:ECS
[List of licence cell permits for other vector products]
```
This library provides only low-level functions. You can create cellpermits  with this library and put it to the permit.txt file manually. Or you can create some high-level function, which will do it automatically. 
Honestly, i created this lib for one purpose: decrypt my s63 charts back to s57. And i never used it to something else.

**Comment by y0913011011** [comment]
thank,sir.i am still learn

**Comment by y0913011011** [comment]
Is there any difference between product.txt and permit.txt? I alse see this structure in the product.txt file,but never seen some hints about HW_ID/M_KEY/M_ID/userpermit information and so on.

**Comment by pavelpasha** [comment]
Yes. There are many difference. You`ll never find a HW_ID and M_KEY in any file. Because it stored secretly. Answers on all your questions  can be bound in S-63_e1.2.0_EN_Jan2015.pdf file. This document tells what s63 is, how it encrypted, It explains every file, you can find in a S63 dataset (including PRODUCTS.TXT and and PERMIT.TXT), it describes it structure, purpose and even give some examples . I am sure that when you read it in its entirety, you will have no more questions.
